stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules

npm_install:
  stage: install
  tags:
    - nodejs
  script:
    - npm cache clean --force
    - npm install

ts_lint:
  stage: test
  tags:
    - nodejs
  script:
    - node_modules/tslint/bin/tslint -c tslint.json -p tsconfig.json

npm_test:
  stage: test
  tags:
    - nodejs
  script:
    - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    - apt-get -y update
    - apt-get -y install google-chrome-stable
    - npm test

build:
  stage: build
  only:
    - master
  tags:
    - nodejs
  script:
    - echo $STAGING_SERVER_ENDPOINTS > src/assets/serverEndpoint.json
    - npm run build:SSR
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  only:
    - master
  tags:
    - ssh
  dependencies:
    - build
  script:
    - chmod -R a+rX,ug+w .
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - ssh-keyscan "$STAGING_FRONTEND_URL" >> ~/.ssh/known_hosts
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - scp -r dist/* "$STAGING_FRONTEND_SCP_URL"
