stages:
  - test
  - build
  - deploy

tslint:
  stage: test
  only:
    - master
    - fixPipeline
  tags:
    - nodejs
  script:
    - npm install tslint
    - node_modules/tslint/bin/tslint -c tslint.json -p tsconfig.json

npmtest:
  stage: test
  only:
    - master
    - fixPipeline
  tags:
    - nodejs
  script:
    - npm install
    - npm test

build:
  stage: build
  only:
    - master
    - fixPipeline
  tags:
    - nodejs
  script:
    - npm install
    - npm run build:SSR
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  only:
    - master
    - fixPipeline
  tags:
    - ssh
  dependencies:
    - build
  script:
    - chmod -R a+rX,ug+w .
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh && echo "$STAGING_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - scp -r dist/* "$STAGING_FRONTEND_SSH_URL"

