stages:
  - install
  - test
  - build
  - compress
  - deploy

install:
  stage: install
  only:
    - master
  tags:
    - nodejs
  script:
    - npm install

test:
  stage: test
  only:
    - master
  tags:
    - nodejs
  script:
    - npm test

build:
  stage: build
  only:
    - master
  tags:
    - nodejs
  script:
    - npm run build:SSR
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  only:
    - master
  tags:
    - ssh
  dependencies:
    - build
  script:
    - chmod -R a+rX,ug+w .
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh && echo "$STAGING_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - scp -r dist/* "$STAGING_FRONTEND_SSH_URL"

