stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  tags:
    - nodejs
  script:
    - npm install
    - npm run prod
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  only:
    - master
  tags:
    - ssh
  dependencies:
    - build
  script:
    - chmod -R a+rX,ug+w .
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh && echo "$STAGING_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - scp -r dist/* "$STAGING_FRONTEND_SSH_URL"

