stages:
  - install
  - test
  - build
  - assets
  - sync_sentry
  - deploy
  - build-beta
  - assets-beta
  - sync_sentry-beta
  - deploy-beta

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_node_modules:
  stage: install
  except:
    - /^i18n-change.*/ix
  tags:
    - nodejs
  script:
    - npm install

ts_lint:
  stage: test
  except:
    - /^i18n-change.*/ix
  tags:
    - nodejs
  script:
    - npm install
    - node_modules/tslint/bin/tslint -c tslint.json -p tsconfig.json

npm_test:
  stage: test
  allow_failure: true
  tags:
    - nodejs
    - angular
  script:
    - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    - apt-get -y update
    - apt-get -y install --allow-unauthenticated google-chrome-stable
    - npm install
    - npm test

build:
  stage: build
  only:
    - master
  tags:
    - nodejs
    - angular
  before_script:
    - sed -ri "s|\"VERSION\"|\"$CI_COMMIT_SHA\"|" src/environments/environment.thm.staging.ts
  script:
    - npm install
    - npm install typescript@3.5.3
    - npm run build:STAGING_THM
  artifacts:
    paths:
      - dist

generate_assets:
  stage: assets
  only:
    - master
  tags:
    - nodejs
  dependencies:
    - build
  script:
    - apt-get -y update
    - apt-get -y install --allow-unauthenticated gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
    - npm install
    - npm install -g angular-http-server
    - cd dist
    - angular-http-server --path browser/ --silent -p 4711 &
    - cd browser/assets/jobs
    - node --experimental-modules GenerateImages.mjs --command=generateLogoImages
    - node --experimental-modules GenerateImages.mjs --command=generateFrontendPreview --host=http://localhost:4711 --root=true
    - node GenerateMetaNodes.js --command=generateLinkImages --baseUrl=https://staging.arsnova.click
    - node GenerateMetaNodes.js --command=generateManifest --baseUrl=https://staging.arsnova.click
    - cd ../../../..
    - npm run compress
  artifacts:
    paths:
      - dist

sync_sentry:
  stage: sync_sentry
  only:
    - master
  tags:
    - nodejs
  dependencies:
    - generate_assets
  image: getsentry/sentry-cli
  script:
    - echo "Create a new release $CI_COMMIT_SHA"
    #- export SENTRY_URL=$SENTRY_BASE_URL
    - export SENTRY_AUTH_TOKEN=$SENTRY_BASE_TOKEN
    - export SENTRY_ORG=$SENTRY_BASE_ORGANIZATION
    - export SENTRY_PROJECT=$SENTRY_BASE_PROJECT
    - sentry-cli releases new $CI_COMMIT_SHA
    - sentry-cli releases set-commits --auto $CI_COMMIT_SHA
    - sentry-cli releases files $CI_COMMIT_SHA upload-sourcemaps $CI_PROJECT_DIR/dist -x .js -x .map --validate --verbose --rewrite --strip-common-prefix
    - sentry-cli releases finalize $CI_COMMIT_SHA
    - echo "Finalized release for $CI_COMMIT_SHA"

deploy:
  stage: deploy
  only:
    - master
  tags:
    - rsync
  dependencies:
    - sync_sentry
  script:
    - chmod -R a+rX,ug+w .
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - ssh-keyscan "$STAGING_FRONTEND_URL" >> ~/.ssh/known_hosts
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - rm dist/*.map
    - rsync -rltgoDqv --delete -e "ssh" dist/* "$STAGING_FRONTEND_SCP_URL"
    - ssh $STAGING_SSH 'touch /home/arsnova/arsnova.click-v2/frontend/deploy.touch'

build-beta:
  stage: build-beta
  only:
    - beta
  tags:
    - nodejs
    - angular
  before_script:
    - sed -ri "s|\"VERSION\"|\"$CI_COMMIT_SHA\"|" src/environments/environment.thm.beta.ts
  script:
    - npm install
    - npm install typescript@3.5.3
    - npm run build:BETA_THM
  artifacts:
    paths:
      - dist

generate_assets-beta:
  stage: assets-beta
  only:
    - beta
  tags:
    - nodejs
  dependencies:
    - build-beta
  script:
    - apt-get -y update
    - apt-get -y install --allow-unauthenticated gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
    - npm install
    - npm install -g angular-http-server
    - cd dist
    - angular-http-server --path browser/ --silent -p 4711 &
    - cd browser/assets/jobs
    - node --experimental-modules GenerateImages.mjs --command=generateLogoImages
    - node --experimental-modules GenerateImages.mjs --command=generateFrontendPreview --host=http://localhost:4711 --root=true
    - node GenerateMetaNodes.js --command=generateLinkImages --baseUrl=https://beta.arsnova.click
    - node GenerateMetaNodes.js --command=generateManifest --baseUrl=https://beta.arsnova.click
    - cd ../../../..
    - npm run compress
  artifacts:
    paths:
      - dist

sync_sentry-beta:
  stage: sync_sentry-beta
  only:
    - beta
  tags:
    - nodejs
  dependencies:
    - generate_assets-beta
  image: getsentry/sentry-cli
  script:
    - echo "Create a new release $CI_COMMIT_SHA"
    #- export SENTRY_URL=$SENTRY_BASE_URL
    - export SENTRY_AUTH_TOKEN=$SENTRY_BASE_TOKEN
    - export SENTRY_ORG=$SENTRY_BASE_ORGANIZATION
    - export SENTRY_PROJECT=$SENTRY_BASE_PROJECT
    - sentry-cli releases new $CI_COMMIT_SHA
    - sentry-cli releases set-commits --auto $CI_COMMIT_SHA
    - sentry-cli releases files $CI_COMMIT_SHA upload-sourcemaps $CI_PROJECT_DIR/dist -x .js -x .map --validate --verbose --rewrite --strip-common-prefix
    - sentry-cli releases finalize $CI_COMMIT_SHA
    - echo "Finalized release for $CI_COMMIT_SHA"

deploy-beta:
  stage: deploy-beta
  only:
    - beta
  tags:
    - rsync
  dependencies:
    - sync_sentry-beta
  script:
    - chmod -R a+rX,ug+w .
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - ssh-keyscan "$STAGING_FRONTEND_URL" >> ~/.ssh/known_hosts
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - rm dist/*.map
    - rsync -rltgoDqv --delete -e "ssh" dist/* "$BETA_FRONTEND_SCP_URL"
    - ssh $STAGING_SSH 'touch /home/arsnova/arsnova.click-v2-beta/frontend/deploy.touch'
